In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("GSSsubset.csv")
df.head()

   id     sex       degree    income   marital  age  height  weight  hrswrk
0   1    MALE     BACHELOR  60967.50  DIVORCED   53      72     190      60
1   2  FEMALE     BACHELOR  60967.50   MARRIED   26      60      97      40
2   4  FEMALE     BACHELOR  10161.25   MARRIED   56      68     160      20
3  14  FEMALE  HIGH SCHOOL  17551.25   MARRIED   40      65     156      37
4  16    MALE  HIGH SCHOOL  17551.25   MARRIED   56      66     210       6

### **1. FILTERING**

#### **Single Filtering**
> Subset rows that meet certain conditions

In [3]:
# Create male participant data

male = df[df['sex'] == 'MALE']
male.head(10)

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,BACHELOR,60967.50,DIVORCED,53,72,190,60
4,16,MALE,HIGH SCHOOL,17551.25,MARRIED,56,66,210,6
5,19,MALE,LT HIGH SCHOOL,15703.75,MARRIED,51,68,170,50
7,27,MALE,HIGH SCHOOL,17551.25,SEPARATED,35,70,180,40
8,28,MALE,BACHELOR,73900.00,MARRIED,57,71,225,40
9,30,MALE,BACHELOR,33255.00,DIVORCED,54,71,165,40
11,38,MALE,HIGH SCHOOL,33255.00,DIVORCED,31,67,150,39
12,40,MALE,BACHELOR,73900.00,MARRIED,35,69,200,50
13,44,MALE,HIGH SCHOOL,24017.50,NEVER MARRIED,26,76,165,45
16,47,MALE,JUNIOR COLLEGE,40645.00,NEVER MARRIED,30,72,185,45

#### **Multiple Filtering**

In [4]:
subset = df[(df['sex'] == 'FEMALE') &
    (df['age'] < 35) &
    (df['marital'] == 'MARRIED') &
    (df['degree'] == 'GRADUATE')]
subset.head()

       id     sex    degree   income  marital  age  height  weight  hrswrk
18     49  FEMALE  GRADUATE  88680.0  MARRIED   32      66     160      40
115   312  FEMALE  GRADUATE  60967.5  MARRIED   30      66     150      47
412  1037  FEMALE  GRADUATE  49882.5  MARRIED   30      61     129      50
747  1920  FEMALE  GRADUATE  88680.0  MARRIED   31      67     180      40
856  2209  FEMALE  GRADUATE  88680.0  MARRIED   34      66     148      30

#### **OR Condition**

In [5]:
df.head(30)

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,BACHELOR,60967.500,DIVORCED,53,72,190,60
1,2,FEMALE,BACHELOR,60967.500,MARRIED,26,60,97,40
2,4,FEMALE,BACHELOR,10161.250,MARRIED,56,68,160,20
3,14,FEMALE,HIGH SCHOOL,17551.250,MARRIED,40,65,156,37
4,16,MALE,HIGH SCHOOL,17551.250,MARRIED,56,66,210,6
5,19,MALE,LT HIGH SCHOOL,15703.750,MARRIED,51,68,170,50
6,21,FEMALE,HIGH SCHOOL,17551.250,DIVORCED,30,62,115,38
7,27,MALE,HIGH SCHOOL,17551.250,SEPARATED,35,70,180,40
8,28,MALE,BACHELOR,73900.000,MARRIED,57,71,225,40
9,30,MALE,BACHELOR,33255.000,DIVORCED,54,71,165,40
10,32,FEMALE,BACHELOR,33255.000,DIVORCED,61,64,128,40
11,38,MALE,HIGH SCHOOL,33255.000,DIVORCED,31,67,150,39
12,40,MALE,BACHELOR,73900.000,MARRIED,35,69,200,50
13,44,MALE,HIGH SCHOOL,24017.500,NEVER MARRIED,26,76,165,45
14,45,FEMALE,BACHELOR,88680.000,SEPARATED,50,67,188,60
15,46,FEMALE,HIGH SCHOOL,33255.000,NEVER MARRIED,43,68,150,40
16,47,MALE,JUNIOR COLLEGE,40645.000,NEVER MARRIED,30,72,185,45
17,48,MALE,HIGH SCHOOL,49882.500,MARRIED,59,70,175,40
18,49,FEMALE,GRADUATE,88680.000,MARRIED,32,66,160,40
19,50,MALE,HIGH SCHOOL,24017.500,MARRIED,32,66,170,40
20,51,FEMALE,GRADUATE,33255.000,MARRIED,52,63,143,40
21,52,MALE,BACHELOR,40645.000,MARRIED,42,68,230,40
22,53,MALE,JUNIOR COLLEGE,40645.000,MARRIED,29,73,245,60
23,56,FEMALE,BACHELOR,1478.000,NEVER MARRIED,24,65,118,16
24,59,FEMALE,BACHELOR,73900.000,NEVER MARRIED,56,66,148,30
25,61,MALE,GRADUATE,15703.750,NEVER MARRIED,51,70,190,14
26,64,FEMALE,GRADUATE,60967.500,NEVER MARRIED,47,64,123,40
27,68,MALE,GRADUATE,158656.952,DIVORCED,57,71,180,70
28,70,MALE,HIGH SCHOOL,15703.750,NEVER MARRIED,32,67,165,40
29,75,FEMALE,GRADUATE,88680.000,MARRIED,39,69,210,60

In [6]:
high_educ = df[(df['degree'] == "BACHELOR")|
    (df['degree'] == 'GRADUATE')]
high_educ.head(20)

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,BACHELOR,60967.500,DIVORCED,53,72,190,60
1,2,FEMALE,BACHELOR,60967.500,MARRIED,26,60,97,40
2,4,FEMALE,BACHELOR,10161.250,MARRIED,56,68,160,20
8,28,MALE,BACHELOR,73900.000,MARRIED,57,71,225,40
9,30,MALE,BACHELOR,33255.000,DIVORCED,54,71,165,40
10,32,FEMALE,BACHELOR,33255.000,DIVORCED,61,64,128,40
12,40,MALE,BACHELOR,73900.000,MARRIED,35,69,200,50
14,45,FEMALE,BACHELOR,88680.000,SEPARATED,50,67,188,60
18,49,FEMALE,GRADUATE,88680.000,MARRIED,32,66,160,40
20,51,FEMALE,GRADUATE,33255.000,MARRIED,52,63,143,40
21,52,MALE,BACHELOR,40645.000,MARRIED,42,68,230,40
23,56,FEMALE,BACHELOR,1478.000,NEVER MARRIED,24,65,118,16
24,59,FEMALE,BACHELOR,73900.000,NEVER MARRIED,56,66,148,30
25,61,MALE,GRADUATE,15703.750,NEVER MARRIED,51,70,190,14
26,64,FEMALE,GRADUATE,60967.500,NEVER MARRIED,47,64,123,40
27,68,MALE,GRADUATE,158656.952,DIVORCED,57,71,180,70
29,75,FEMALE,GRADUATE,88680.000,MARRIED,39,69,210,60
30,77,MALE,BACHELOR,103460.000,MARRIED,54,70,200,60
37,102,MALE,GRADUATE,49882.500,NEVER MARRIED,32,75,180,55
38,106,MALE,BACHELOR,33255.000,MARRIED,41,65,170,50

### **2. SELECTION**

#### **Single Column Selection**

In [7]:
df['sex']

0        MALE
1      FEMALE
2      FEMALE
3      FEMALE
4        MALE
        ...
989      MALE
990      MALE
991      MALE
992      MALE
993    FEMALE
Name: sex, Length: 994, dtype: str

In [8]:
gender = df['sex']
gender.head()

0      MALE
1    FEMALE
2    FEMALE
3    FEMALE
4      MALE
Name: sex, dtype: str

#### **Select Multiple Columns**

In [9]:
### First option
cols = ['sex', 'age', 'income', 'marital']
selected_cols = df[cols]
selected_cols.head()

      sex  age    income   marital
0    MALE   53  60967.50  DIVORCED
1  FEMALE   26  60967.50   MARRIED
2  FEMALE   56  10161.25   MARRIED
3  FEMALE   40  17551.25   MARRIED
4    MALE   56  17551.25   MARRIED

In [10]:
## Second option
selected_cols = df[['sex', 'age', 'income', 'marital']]
selected_cols.head()

      sex  age    income   marital
0    MALE   53  60967.50  DIVORCED
1  FEMALE   26  60967.50   MARRIED
2  FEMALE   56  10161.25   MARRIED
3  FEMALE   40  17551.25   MARRIED
4    MALE   56  17551.25   MARRIED

In [11]:
## Third option
drop_cols = df.drop(columns = ['id', 'degree', 'height', 'weight', 'hrswrk'])
drop_cols.head()

      sex    income   marital  age
0    MALE  60967.50  DIVORCED   53
1  FEMALE  60967.50   MARRIED   26
2  FEMALE  10161.25   MARRIED   56
3  FEMALE  17551.25   MARRIED   40
4    MALE  17551.25   MARRIED   56

### **3. GROUP BY AND SUMMARIZE**

In [12]:
print("="*100)
print(" GROUP BY AND SUMMARIZING")
print("="*100)

print("Mean Income by Education levels")

income_by_educ = df.groupby('degree')['income'].mean().sort_values(ascending = False)
income_by_educ

====================================================================================================
 GROUP BY AND SUMMARIZING
====================================================================================================
Mean Income by Education levels

degree
GRADUATE          68457.773552
BACHELOR          47738.621187
JUNIOR COLLEGE    30580.141304
HIGH SCHOOL       28309.892098
LT HIGH SCHOOL    18412.616883
Name: income, dtype: float64

In [13]:
print("="*100)
print(" GROUP BY AND SUMMARIZING")
print("="*100)

print("Median Income by Education levels")

income_by_educ = df.groupby('degree')['income'].median().sort_values(ascending = False)
income_by_educ

====================================================================================================
 GROUP BY AND SUMMARIZING
====================================================================================================
Median Income by Education levels

degree
GRADUATE          49882.50
BACHELOR          40645.00
JUNIOR COLLEGE    27712.50
HIGH SCHOOL       24017.50
LT HIGH SCHOOL    15703.75
Name: income, dtype: float64

In [14]:
print("="*100)
print(" GROUP BY AND SUMMARIZING")
print("="*100)

print("Mean Income by Marital Status")

income_by_mar = df.groupby('marital')['income'].mean().sort_values(ascending = False)
income_by_mar

====================================================================================================
 GROUP BY AND SUMMARIZING
====================================================================================================
Mean Income by Marital Status

marital
MARRIED          43838.108058
DIVORCED         39881.177721
SEPARATED        25903.775730
NEVER MARRIED    25828.277524
WIDOWED          23827.618056
Name: income, dtype: float64

In [15]:
## Multiple grouping by and summarizing
print("="*100)
print(" GROUP BY AND SUMMARIZING")
print("="*100)

print("Mean Income by Education and Gender levels")

income_by_educ = df.groupby(['sex','degree'])['income'].mean()
income_by_educ

====================================================================================================
 GROUP BY AND SUMMARIZING
====================================================================================================
Mean Income by Education and Gender levels

sex     degree
FEMALE  BACHELOR          34269.353010
        GRADUATE          52381.502655
        HIGH SCHOOL       21630.135693
        JUNIOR COLLEGE    22180.077273
        LT HIGH SCHOOL    11350.578125
MALE    BACHELOR          60334.881241
        GRADUATE          82374.545373
        HIGH SCHOOL       34749.177272
        JUNIOR COLLEGE    43066.722973
        LT HIGH SCHOOL    23434.511111
Name: income, dtype: float64

##### **Reset the index for the series**

In [16]:
income_by_educ = df.groupby(['sex','degree'])['income'].mean().reset_index()
income_by_educ

      sex          degree        income
0  FEMALE        BACHELOR  34269.353010
1  FEMALE        GRADUATE  52381.502655
2  FEMALE     HIGH SCHOOL  21630.135693
3  FEMALE  JUNIOR COLLEGE  22180.077273
4  FEMALE  LT HIGH SCHOOL  11350.578125
5    MALE        BACHELOR  60334.881241
6    MALE        GRADUATE  82374.545373
7    MALE     HIGH SCHOOL  34749.177272
8    MALE  JUNIOR COLLEGE  43066.722973
9    MALE  LT HIGH SCHOOL  23434.511111

##### **Unstack the table**

In [17]:
income_by_educ = df.groupby(['sex','degree'])['income'].mean().unstack()
income_by_educ

degree,BACHELOR,GRADUATE,HIGH SCHOOL,JUNIOR COLLEGE,LT HIGH SCHOOL
sex,,,,,
FEMALE,34269.353010,52381.502655,21630.135693,22180.077273,11350.578125
MALE,60334.881241,82374.545373,34749.177272,43066.722973,23434.511111

In [18]:
income_by_educ = df.groupby(['sex','marital','degree'])['income'].mean().unstack()
income_by_educ

degree                    BACHELOR       GRADUATE   HIGH SCHOOL  \
sex    marital
FEMALE DIVORCED       39995.969556   44455.468750  22684.660714
       MARRIED        34316.479846   54501.250000  24494.319813
       NEVER MARRIED  28860.589286   52449.618143  18487.483108
       SEPARATED      88680.000000   40645.000000  18490.395833
       WIDOWED        30021.875000            NaN  18746.691176
MALE   DIVORCED       56866.050000  109717.882909  39306.581451
       MARRIED        70023.384629   86758.384400  44076.445458
       NEVER MARRIED  39767.437500   43550.613636  21546.168831
       SEPARATED               NaN   68531.425500  15080.218750
       WIDOWED        22862.812500   88680.000000  26683.178571

degree                JUNIOR COLLEGE  LT HIGH SCHOOL
sex    marital
FEMALE DIVORCED         25310.750000    15149.500000
       MARRIED          19109.576087     9131.928571
       NEVER MARRIED    23555.625000    11131.187500
       SEPARATED        24941.250000     8313.750000
       WIDOWED                   NaN    15565.187500
MALE   DIVORCED         61363.392857    30252.812500
       MARRIED          41825.347222    23618.440000
       NEVER MARRIED    34086.375000    19715.464286
       SEPARATED        20322.500000    16812.250000
       WIDOWED          49882.500000             NaN

##### **Advanced Grouping and Multiple Aggregation**

In [19]:
summary = df.groupby('degree').agg({
    'income':['mean', 'median', 'std', 'var', 'count'],
    'age':['mean', 'median'],
    'height': ['mean', 'median']
})
summary

                      income                                              \
                        mean    median           std           var count
degree
BACHELOR        47738.621187  40645.00  38036.482608  1.446774e+09   209
GRADUATE        68457.773552  49882.50  47526.992948  2.258815e+09   125
HIGH SCHOOL     28309.892098  24017.50  26671.333894  7.113601e+08   491
JUNIOR COLLEGE  30580.141304  27712.50  20292.993851  4.118056e+08    92
LT HIGH SCHOOL  18412.616883  15703.75  13324.116851  1.775321e+08    77

                      age            height
                     mean median       mean median
degree
BACHELOR        44.550239   44.0  68.057416   68.0
GRADUATE        47.624000   47.0  68.176000   69.0
HIGH SCHOOL     43.602851   43.0  67.173116   67.0
JUNIOR COLLEGE  42.413043   42.5  66.858696   67.0
LT HIGH SCHOOL  47.363636   49.0  66.636364   66.0

#### **FEATURE ENGINEERING**

In [20]:
df.head()

   id     sex       degree    income   marital  age  height  weight  hrswrk
0   1    MALE     BACHELOR  60967.50  DIVORCED   53      72     190      60
1   2  FEMALE     BACHELOR  60967.50   MARRIED   26      60      97      40
2   4  FEMALE     BACHELOR  10161.25   MARRIED   56      68     160      20
3  14  FEMALE  HIGH SCHOOL  17551.25   MARRIED   40      65     156      37
4  16    MALE  HIGH SCHOOL  17551.25   MARRIED   56      66     210       6

##### **Create Income Categories**

In [21]:
mean_income = df['income'].mean()
print(f"Mean: {mean_income}")

Mean: 36887.21835211268

In [22]:
df['Income_Category'] = np.where(df['income'] >= mean_income,
                                 'HIGH INCOME','LOW INCOME')
df.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk,Income_Category
0,1,MALE,BACHELOR,60967.50,DIVORCED,53,72,190,60,HIGH INCOME
1,2,FEMALE,BACHELOR,60967.50,MARRIED,26,60,97,40,HIGH INCOME
2,4,FEMALE,BACHELOR,10161.25,MARRIED,56,68,160,20,LOW INCOME
3,14,FEMALE,HIGH SCHOOL,17551.25,MARRIED,40,65,156,37,LOW INCOME
4,16,MALE,HIGH SCHOOL,17551.25,MARRIED,56,66,210,6,LOW INCOME

##### **Frequency of Income Category**

In [24]:
freq = df['Income_Category'].value_counts()
freq

Income_Category
LOW INCOME     637
HIGH INCOME    357
Name: count, dtype: int64

##### **Descriptive Statistics**

In [25]:
df.drop(columns = ['id']).describe()

              income         age      height      weight      hrswrk
count     994.000000  994.000000  994.000000  994.000000  994.000000
mean    36887.218352   44.488934   67.414487  181.318913   42.640845
std     34702.256068   13.126865    4.037741   41.641615   14.394974
min       369.500000   19.000000   57.000000   90.000000    1.000000
25%     15703.750000   33.000000   64.000000  150.000000   38.000000
50%     27712.500000   44.000000   67.000000  175.000000   40.000000
75%     49882.500000   55.000000   70.000000  205.000000   50.000000
max    158656.952000   79.000000   79.000000  410.000000   89.000000

In [27]:
bins = [19, 35, 45, 55, float('inf')]
labels = ['YOUNG', 'YOUNG ADULT', 'MIDDLE ADULT', 'OLDER ADULT']
df['Age_Cat'] = pd.cut(df['age'],
                       bins = bins,
                       labels = labels,
                       right = False)
df.head()

,id,sex,degree,income,marital,age,height,weight,hrswrk,Income_Category,Age_Cat
0,1,MALE,BACHELOR,60967.50,DIVORCED,53,72,190,60,HIGH INCOME,MIDDLE ADULT
1,2,FEMALE,BACHELOR,60967.50,MARRIED,26,60,97,40,HIGH INCOME,YOUNG
2,4,FEMALE,BACHELOR,10161.25,MARRIED,56,68,160,20,LOW INCOME,OLDER ADULT
3,14,FEMALE,HIGH SCHOOL,17551.25,MARRIED,40,65,156,37,LOW INCOME,YOUNG ADULT
4,16,MALE,HIGH SCHOOL,17551.25,MARRIED,56,66,210,6,LOW INCOME,OLDER ADULT

In [28]:
freq = df['Age_Cat'].value_counts()
freq

Age_Cat
YOUNG           273
OLDER ADULT     257
YOUNG ADULT     234
MIDDLE ADULT    230
Name: count, dtype: int64

##### **Frequency Distribution Table**

In [29]:
df.describe(include = ['object', 'category'])

         sex       degree  marital Income_Category Age_Cat
count    994          994      994             994     994
unique     2            5        5               2       4
top     MALE  HIGH SCHOOL  MARRIED      LOW INCOME   YOUNG
freq     507          491      480             637     273